version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - "9991:8080"
  web:
   environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
   build: .
   ports:
      - "9992:8080"