version: '3.7'
services:
  postgres:
    image: postgres:11.0
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: postgres_db
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
      image: "redis:alpine"